### ISSUE TITLE
Option for hot app reload?

### ISSUE THREAD

**Issue by sirceljm** [weexteam/weex-pack#112]
Hi,

Is there an option to reload app after you make a change without rerunning `weexpack run android`.

I shake the phone as with React Native and get two options in chinese. First one sends me to QR code scanner and the second one looks like cancel to me.

Thanks

**Comment by kfeagle** [comment]
@misakuo

**Comment by JackPu** [comment]
It is a good advise. I think live reloading improves our development experience. We suppose that users can add a flag `--hot` to use the feature in maybe next version.

**Comment by dts** [comment]
@JackPu - I have succeeded in creating a 'weex' target mode for WebPack, which uses the stream.fetch() mechanism instead of XHR.  I've also gotten an HMR client working as well, I've just gotten stuck at trying to get the new options hash sticking in old Vue components (as listed in the hot reloader api) - I'm running up against a Vue 2.1.9 issue and/or some "extends" logic that isn't working the way I expect `var newCtor = record.Ctor.super.extend(options);` doesn't behave the way I expect it to - the render function doesn't get inherited from the new options hash.
